// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: proto/workitem.proto

package workitem

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkItemService_CreateWorkItems_FullMethodName = "/chura.workitem.v1.WorkItemService/CreateWorkItems"
	WorkItemService_GetWorkItem_FullMethodName     = "/chura.workitem.v1.WorkItemService/GetWorkItem"
	WorkItemService_ListWorkItems_FullMethodName   = "/chura.workitem.v1.WorkItemService/ListWorkItems"
	WorkItemService_UpdateWorkItem_FullMethodName  = "/chura.workitem.v1.WorkItemService/UpdateWorkItem"
	WorkItemService_DeleteWorkItem_FullMethodName  = "/chura.workitem.v1.WorkItemService/DeleteWorkItem"
)

// WorkItemServiceClient is the client API for WorkItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkItemServiceClient interface {
	CreateWorkItems(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CreateWorkItemRequest, WorkItem], error)
	GetWorkItem(ctx context.Context, in *GetWorkItemRequest, opts ...grpc.CallOption) (*WorkItem, error)
	ListWorkItems(ctx context.Context, in *ListWorkItemsRequest, opts ...grpc.CallOption) (*ListWorkItemsResponse, error)
	UpdateWorkItem(ctx context.Context, in *UpdateWorkItemRequest, opts ...grpc.CallOption) (*WorkItem, error)
	DeleteWorkItem(ctx context.Context, in *DeleteWorkItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type workItemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkItemServiceClient(cc grpc.ClientConnInterface) WorkItemServiceClient {
	return &workItemServiceClient{cc}
}

func (c *workItemServiceClient) CreateWorkItems(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CreateWorkItemRequest, WorkItem], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkItemService_ServiceDesc.Streams[0], WorkItemService_CreateWorkItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateWorkItemRequest, WorkItem]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkItemService_CreateWorkItemsClient = grpc.BidiStreamingClient[CreateWorkItemRequest, WorkItem]

func (c *workItemServiceClient) GetWorkItem(ctx context.Context, in *GetWorkItemRequest, opts ...grpc.CallOption) (*WorkItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkItem)
	err := c.cc.Invoke(ctx, WorkItemService_GetWorkItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workItemServiceClient) ListWorkItems(ctx context.Context, in *ListWorkItemsRequest, opts ...grpc.CallOption) (*ListWorkItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkItemsResponse)
	err := c.cc.Invoke(ctx, WorkItemService_ListWorkItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workItemServiceClient) UpdateWorkItem(ctx context.Context, in *UpdateWorkItemRequest, opts ...grpc.CallOption) (*WorkItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkItem)
	err := c.cc.Invoke(ctx, WorkItemService_UpdateWorkItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workItemServiceClient) DeleteWorkItem(ctx context.Context, in *DeleteWorkItemRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkItemService_DeleteWorkItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkItemServiceServer is the server API for WorkItemService service.
// All implementations must embed UnimplementedWorkItemServiceServer
// for forward compatibility.
type WorkItemServiceServer interface {
	CreateWorkItems(grpc.BidiStreamingServer[CreateWorkItemRequest, WorkItem]) error
	GetWorkItem(context.Context, *GetWorkItemRequest) (*WorkItem, error)
	ListWorkItems(context.Context, *ListWorkItemsRequest) (*ListWorkItemsResponse, error)
	UpdateWorkItem(context.Context, *UpdateWorkItemRequest) (*WorkItem, error)
	DeleteWorkItem(context.Context, *DeleteWorkItemRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedWorkItemServiceServer()
}

// UnimplementedWorkItemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkItemServiceServer struct{}

func (UnimplementedWorkItemServiceServer) CreateWorkItems(grpc.BidiStreamingServer[CreateWorkItemRequest, WorkItem]) error {
	return status.Error(codes.Unimplemented, "method CreateWorkItems not implemented")
}
func (UnimplementedWorkItemServiceServer) GetWorkItem(context.Context, *GetWorkItemRequest) (*WorkItem, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkItem not implemented")
}
func (UnimplementedWorkItemServiceServer) ListWorkItems(context.Context, *ListWorkItemsRequest) (*ListWorkItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkItems not implemented")
}
func (UnimplementedWorkItemServiceServer) UpdateWorkItem(context.Context, *UpdateWorkItemRequest) (*WorkItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkItem not implemented")
}
func (UnimplementedWorkItemServiceServer) DeleteWorkItem(context.Context, *DeleteWorkItemRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkItem not implemented")
}
func (UnimplementedWorkItemServiceServer) mustEmbedUnimplementedWorkItemServiceServer() {}
func (UnimplementedWorkItemServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkItemServiceServer will
// result in compilation errors.
type UnsafeWorkItemServiceServer interface {
	mustEmbedUnimplementedWorkItemServiceServer()
}

func RegisterWorkItemServiceServer(s grpc.ServiceRegistrar, srv WorkItemServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkItemService_ServiceDesc, srv)
}

func _WorkItemService_CreateWorkItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkItemServiceServer).CreateWorkItems(&grpc.GenericServerStream[CreateWorkItemRequest, WorkItem]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkItemService_CreateWorkItemsServer = grpc.BidiStreamingServer[CreateWorkItemRequest, WorkItem]

func _WorkItemService_GetWorkItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemServiceServer).GetWorkItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemService_GetWorkItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemServiceServer).GetWorkItem(ctx, req.(*GetWorkItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkItemService_ListWorkItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemServiceServer).ListWorkItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemService_ListWorkItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemServiceServer).ListWorkItems(ctx, req.(*ListWorkItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkItemService_UpdateWorkItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemServiceServer).UpdateWorkItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemService_UpdateWorkItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemServiceServer).UpdateWorkItem(ctx, req.(*UpdateWorkItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkItemService_DeleteWorkItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkItemServiceServer).DeleteWorkItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkItemService_DeleteWorkItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkItemServiceServer).DeleteWorkItem(ctx, req.(*DeleteWorkItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkItemService_ServiceDesc is the grpc.ServiceDesc for WorkItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chura.workitem.v1.WorkItemService",
	HandlerType: (*WorkItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkItem",
			Handler:    _WorkItemService_GetWorkItem_Handler,
		},
		{
			MethodName: "ListWorkItems",
			Handler:    _WorkItemService_ListWorkItems_Handler,
		},
		{
			MethodName: "UpdateWorkItem",
			Handler:    _WorkItemService_UpdateWorkItem_Handler,
		},
		{
			MethodName: "DeleteWorkItem",
			Handler:    _WorkItemService_DeleteWorkItem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateWorkItems",
			Handler:       _WorkItemService_CreateWorkItems_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/workitem.proto",
}
