// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Multiple reporter associations.
	AddWorkItemReporter(ctx context.Context, arg AddWorkItemReporterParams) error
	// Work item CRUD queries.
	// sqlc generates Go methods from the annotations below.
	CreateWorkItem(ctx context.Context, arg CreateWorkItemParams) (WorkItem, error)
	DeleteWorkItem(ctx context.Context, id string) error
	GetWorkItem(ctx context.Context, id string) (WorkItem, error)
	ListWorkItemReporterIDs(ctx context.Context, workItemID string) ([]pgtype.Text, error)
	ListWorkItems(ctx context.Context, projectID string) ([]WorkItem, error)
	RemoveAllWorkItemReporters(ctx context.Context, workItemID string) error
	RemoveWorkItemReporter(ctx context.Context, arg RemoveWorkItemReporterParams) error
	UpdateWorkItem(ctx context.Context, arg UpdateWorkItemParams) (WorkItem, error)
}

var _ Querier = (*Queries)(nil)
