// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_items.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkItemReporter = `-- name: AddWorkItemReporter :exec

INSERT INTO work_item_reporters (id, work_item_id, reporter_id)
VALUES ($1, $2, $3)
ON CONFLICT (work_item_id, reporter_id) DO NOTHING
`

type AddWorkItemReporterParams struct {
	ID         string      `json:"id"`
	WorkItemID string      `json:"work_item_id"`
	ReporterID pgtype.Text `json:"reporter_id"`
}

// Multiple reporter associations.
func (q *Queries) AddWorkItemReporter(ctx context.Context, arg AddWorkItemReporterParams) error {
	_, err := q.db.Exec(ctx, addWorkItemReporter, arg.ID, arg.WorkItemID, arg.ReporterID)
	return err
}

const createWorkItem = `-- name: CreateWorkItem :one

INSERT INTO work_items (
    id,
    project_id,
    title,
    description,
    type,
    status,
    priority,
    assignee_id,
    story_points,
    features
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, project_id, title, description, type, status, priority, assignee_id, story_points, features, created_at, updated_at
`

type CreateWorkItemParams struct {
	ID          string      `json:"id"`
	ProjectID   string      `json:"project_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Type        string      `json:"type"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	AssigneeID  pgtype.Text `json:"assignee_id"`
	StoryPoints int32       `json:"story_points"`
	Features    []byte      `json:"features"`
}

// Work item CRUD queries.
// sqlc generates Go methods from the annotations below.
func (q *Queries) CreateWorkItem(ctx context.Context, arg CreateWorkItemParams) (WorkItem, error) {
	row := q.db.QueryRow(ctx, createWorkItem,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.StoryPoints,
		arg.Features,
	)
	var i WorkItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.StoryPoints,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkItem = `-- name: DeleteWorkItem :exec
DELETE FROM work_items
WHERE id = $1
`

func (q *Queries) DeleteWorkItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWorkItem, id)
	return err
}

const getWorkItem = `-- name: GetWorkItem :one
SELECT id, project_id, title, description, type, status, priority, assignee_id, story_points, features, created_at, updated_at
FROM work_items
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetWorkItem(ctx context.Context, id string) (WorkItem, error) {
	row := q.db.QueryRow(ctx, getWorkItem, id)
	var i WorkItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.StoryPoints,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkItemReporterIDs = `-- name: ListWorkItemReporterIDs :many
SELECT reporter_id
FROM work_item_reporters
WHERE work_item_id = $1
  AND reporter_id IS NOT NULL
ORDER BY reporter_id ASC
`

func (q *Queries) ListWorkItemReporterIDs(ctx context.Context, workItemID string) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listWorkItemReporterIDs, workItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var reporter_id pgtype.Text
		if err := rows.Scan(&reporter_id); err != nil {
			return nil, err
		}
		items = append(items, reporter_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkItems = `-- name: ListWorkItems :many
SELECT id, project_id, title, description, type, status, priority, assignee_id, story_points, features, created_at, updated_at
FROM work_items
WHERE project_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListWorkItems(ctx context.Context, projectID string) ([]WorkItem, error) {
	rows, err := q.db.Query(ctx, listWorkItems, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkItem
	for rows.Next() {
		var i WorkItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.StoryPoints,
			&i.Features,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllWorkItemReporters = `-- name: RemoveAllWorkItemReporters :exec
DELETE FROM work_item_reporters
WHERE work_item_id = $1
`

func (q *Queries) RemoveAllWorkItemReporters(ctx context.Context, workItemID string) error {
	_, err := q.db.Exec(ctx, removeAllWorkItemReporters, workItemID)
	return err
}

const removeWorkItemReporter = `-- name: RemoveWorkItemReporter :exec
DELETE FROM work_item_reporters
WHERE work_item_id = $1
  AND reporter_id = $2
`

type RemoveWorkItemReporterParams struct {
	WorkItemID string      `json:"work_item_id"`
	ReporterID pgtype.Text `json:"reporter_id"`
}

func (q *Queries) RemoveWorkItemReporter(ctx context.Context, arg RemoveWorkItemReporterParams) error {
	_, err := q.db.Exec(ctx, removeWorkItemReporter, arg.WorkItemID, arg.ReporterID)
	return err
}

const updateWorkItem = `-- name: UpdateWorkItem :one
UPDATE work_items
SET
    project_id = $2,
    title = $3,
    description = $4,
    type = $5,
    status = $6,
    priority = $7,
    assignee_id = $8,
    story_points = $9,
    features = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, title, description, type, status, priority, assignee_id, story_points, features, created_at, updated_at
`

type UpdateWorkItemParams struct {
	ID          string      `json:"id"`
	ProjectID   string      `json:"project_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Type        string      `json:"type"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	AssigneeID  pgtype.Text `json:"assignee_id"`
	StoryPoints int32       `json:"story_points"`
	Features    []byte      `json:"features"`
}

func (q *Queries) UpdateWorkItem(ctx context.Context, arg UpdateWorkItemParams) (WorkItem, error) {
	row := q.db.QueryRow(ctx, updateWorkItem,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.StoryPoints,
		arg.Features,
	)
	var i WorkItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.StoryPoints,
		&i.Features,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
