// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: internal/adapter/grpc/proto/workitem.proto

package workitem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkItemType int32

const (
	WorkItemType_WORK_ITEM_TYPE_UNSPECIFIED WorkItemType = 0
	WorkItemType_TASK                       WorkItemType = 1
	WorkItemType_USER_STORY                 WorkItemType = 2
	WorkItemType_BUG                        WorkItemType = 3
)

// Enum value maps for WorkItemType.
var (
	WorkItemType_name = map[int32]string{
		0: "WORK_ITEM_TYPE_UNSPECIFIED",
		1: "TASK",
		2: "USER_STORY",
		3: "BUG",
	}
	WorkItemType_value = map[string]int32{
		"WORK_ITEM_TYPE_UNSPECIFIED": 0,
		"TASK":                       1,
		"USER_STORY":                 2,
		"BUG":                        3,
	}
)

func (x WorkItemType) Enum() *WorkItemType {
	p := new(WorkItemType)
	*p = x
	return p
}

func (x WorkItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_adapter_grpc_proto_workitem_proto_enumTypes[0].Descriptor()
}

func (WorkItemType) Type() protoreflect.EnumType {
	return &file_internal_adapter_grpc_proto_workitem_proto_enumTypes[0]
}

func (x WorkItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkItemType.Descriptor instead.
func (WorkItemType) EnumDescriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{0}
}

type WorkItemStatus int32

const (
	WorkItemStatus_WORK_ITEM_STATUS_UNSPECIFIED WorkItemStatus = 0
	WorkItemStatus_TO_DO                        WorkItemStatus = 1
	WorkItemStatus_IN_PROGRESS                  WorkItemStatus = 2
	WorkItemStatus_REVIEW                       WorkItemStatus = 3
	WorkItemStatus_DONE                         WorkItemStatus = 4
	WorkItemStatus_BLOCKED                      WorkItemStatus = 5
)

// Enum value maps for WorkItemStatus.
var (
	WorkItemStatus_name = map[int32]string{
		0: "WORK_ITEM_STATUS_UNSPECIFIED",
		1: "TO_DO",
		2: "IN_PROGRESS",
		3: "REVIEW",
		4: "DONE",
		5: "BLOCKED",
	}
	WorkItemStatus_value = map[string]int32{
		"WORK_ITEM_STATUS_UNSPECIFIED": 0,
		"TO_DO":                        1,
		"IN_PROGRESS":                  2,
		"REVIEW":                       3,
		"DONE":                         4,
		"BLOCKED":                      5,
	}
)

func (x WorkItemStatus) Enum() *WorkItemStatus {
	p := new(WorkItemStatus)
	*p = x
	return p
}

func (x WorkItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_adapter_grpc_proto_workitem_proto_enumTypes[1].Descriptor()
}

func (WorkItemStatus) Type() protoreflect.EnumType {
	return &file_internal_adapter_grpc_proto_workitem_proto_enumTypes[1]
}

func (x WorkItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkItemStatus.Descriptor instead.
func (WorkItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{1}
}

type WorkItemPriority int32

const (
	WorkItemPriority_WORK_ITEM_PRIORITY_UNSPECIFIED WorkItemPriority = 0
	WorkItemPriority_LOW                            WorkItemPriority = 1
	WorkItemPriority_MEDIUM                         WorkItemPriority = 2
	WorkItemPriority_HIGH                           WorkItemPriority = 3
	WorkItemPriority_CRITICAL                       WorkItemPriority = 4
)

// Enum value maps for WorkItemPriority.
var (
	WorkItemPriority_name = map[int32]string{
		0: "WORK_ITEM_PRIORITY_UNSPECIFIED",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	WorkItemPriority_value = map[string]int32{
		"WORK_ITEM_PRIORITY_UNSPECIFIED": 0,
		"LOW":                            1,
		"MEDIUM":                         2,
		"HIGH":                           3,
		"CRITICAL":                       4,
	}
)

func (x WorkItemPriority) Enum() *WorkItemPriority {
	p := new(WorkItemPriority)
	*p = x
	return p
}

func (x WorkItemPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkItemPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_adapter_grpc_proto_workitem_proto_enumTypes[2].Descriptor()
}

func (WorkItemPriority) Type() protoreflect.EnumType {
	return &file_internal_adapter_grpc_proto_workitem_proto_enumTypes[2]
}

func (x WorkItemPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkItemPriority.Descriptor instead.
func (WorkItemPriority) EnumDescriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{2}
}

type WorkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type          WorkItemType           `protobuf:"varint,5,opt,name=type,proto3,enum=chura.workitem.v1.WorkItemType" json:"type,omitempty"`
	Status        WorkItemStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=chura.workitem.v1.WorkItemStatus" json:"status,omitempty"`
	Priority      WorkItemPriority       `protobuf:"varint,7,opt,name=priority,proto3,enum=chura.workitem.v1.WorkItemPriority" json:"priority,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,8,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	ReporterId    string                 `protobuf:"bytes,9,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	StoryPoints   int32                  `protobuf:"varint,10,opt,name=story_points,json=storyPoints,proto3" json:"story_points,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Features      *structpb.Struct       `protobuf:"bytes,13,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItem) Reset() {
	*x = WorkItem{}
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItem) ProtoMessage() {}

func (x *WorkItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItem.ProtoReflect.Descriptor instead.
func (*WorkItem) Descriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{0}
}

func (x *WorkItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkItem) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *WorkItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WorkItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkItem) GetType() WorkItemType {
	if x != nil {
		return x.Type
	}
	return WorkItemType_WORK_ITEM_TYPE_UNSPECIFIED
}

func (x *WorkItem) GetStatus() WorkItemStatus {
	if x != nil {
		return x.Status
	}
	return WorkItemStatus_WORK_ITEM_STATUS_UNSPECIFIED
}

func (x *WorkItem) GetPriority() WorkItemPriority {
	if x != nil {
		return x.Priority
	}
	return WorkItemPriority_WORK_ITEM_PRIORITY_UNSPECIFIED
}

func (x *WorkItem) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *WorkItem) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *WorkItem) GetStoryPoints() int32 {
	if x != nil {
		return x.StoryPoints
	}
	return 0
}

func (x *WorkItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WorkItem) GetFeatures() *structpb.Struct {
	if x != nil {
		return x.Features
	}
	return nil
}

type CreateWorkItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkItem      *WorkItemInput         `protobuf:"bytes,1,opt,name=work_item,json=workItem,proto3" json:"work_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkItemRequest) Reset() {
	*x = CreateWorkItemRequest{}
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkItemRequest) ProtoMessage() {}

func (x *CreateWorkItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkItemRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkItemRequest) GetWorkItem() *WorkItemInput {
	if x != nil {
		return x.WorkItem
	}
	return nil
}

type UpdateWorkItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkItem      *WorkItemInput         `protobuf:"bytes,2,opt,name=work_item,json=workItem,proto3" json:"work_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkItemRequest) Reset() {
	*x = UpdateWorkItemRequest{}
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkItemRequest) ProtoMessage() {}

func (x *UpdateWorkItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateWorkItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkItemRequest) GetWorkItem() *WorkItemInput {
	if x != nil {
		return x.WorkItem
	}
	return nil
}

type WorkItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          WorkItemType           `protobuf:"varint,4,opt,name=type,proto3,enum=chura.workitem.v1.WorkItemType" json:"type,omitempty"`
	Status        WorkItemStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=chura.workitem.v1.WorkItemStatus" json:"status,omitempty"`
	Priority      WorkItemPriority       `protobuf:"varint,6,opt,name=priority,proto3,enum=chura.workitem.v1.WorkItemPriority" json:"priority,omitempty"`
	AssigneeId    string                 `protobuf:"bytes,7,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"`
	ReporterId    string                 `protobuf:"bytes,8,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	StoryPoints   int32                  `protobuf:"varint,9,opt,name=story_points,json=storyPoints,proto3" json:"story_points,omitempty"`
	Features      *structpb.Struct       `protobuf:"bytes,10,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItemInput) Reset() {
	*x = WorkItemInput{}
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItemInput) ProtoMessage() {}

func (x *WorkItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItemInput.ProtoReflect.Descriptor instead.
func (*WorkItemInput) Descriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{3}
}

func (x *WorkItemInput) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *WorkItemInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WorkItemInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkItemInput) GetType() WorkItemType {
	if x != nil {
		return x.Type
	}
	return WorkItemType_WORK_ITEM_TYPE_UNSPECIFIED
}

func (x *WorkItemInput) GetStatus() WorkItemStatus {
	if x != nil {
		return x.Status
	}
	return WorkItemStatus_WORK_ITEM_STATUS_UNSPECIFIED
}

func (x *WorkItemInput) GetPriority() WorkItemPriority {
	if x != nil {
		return x.Priority
	}
	return WorkItemPriority_WORK_ITEM_PRIORITY_UNSPECIFIED
}

func (x *WorkItemInput) GetAssigneeId() string {
	if x != nil {
		return x.AssigneeId
	}
	return ""
}

func (x *WorkItemInput) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *WorkItemInput) GetStoryPoints() int32 {
	if x != nil {
		return x.StoryPoints
	}
	return 0
}

func (x *WorkItemInput) GetFeatures() *structpb.Struct {
	if x != nil {
		return x.Features
	}
	return nil
}

type GetWorkItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkItemRequest) Reset() {
	*x = GetWorkItemRequest{}
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkItemRequest) ProtoMessage() {}

func (x *GetWorkItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkItemRequest.ProtoReflect.Descriptor instead.
func (*GetWorkItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWorkItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkItemsRequest) Reset() {
	*x = ListWorkItemsRequest{}
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkItemsRequest) ProtoMessage() {}

func (x *ListWorkItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkItemsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkItemsRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkItemsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListWorkItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkItems     []*WorkItem            `protobuf:"bytes,1,rep,name=work_items,json=workItems,proto3" json:"work_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkItemsResponse) Reset() {
	*x = ListWorkItemsResponse{}
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkItemsResponse) ProtoMessage() {}

func (x *ListWorkItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkItemsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkItemsResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkItemsResponse) GetWorkItems() []*WorkItem {
	if x != nil {
		return x.WorkItems
	}
	return nil
}

type DeleteWorkItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkItemRequest) Reset() {
	*x = DeleteWorkItemRequest{}
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkItemRequest) ProtoMessage() {}

func (x *DeleteWorkItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapter_grpc_proto_workitem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWorkItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_adapter_grpc_proto_workitem_proto protoreflect.FileDescriptor

const file_internal_adapter_grpc_proto_workitem_proto_rawDesc = "" +
	"\n" +
	"*internal/adapter/grpc/proto/workitem.proto\x12\x11chura.workitem.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x04\n" +
	"\bWorkItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x123\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1f.chura.workitem.v1.WorkItemTypeR\x04type\x129\n" +
	"\x06status\x18\x06 \x01(\x0e2!.chura.workitem.v1.WorkItemStatusR\x06status\x12?\n" +
	"\bpriority\x18\a \x01(\x0e2#.chura.workitem.v1.WorkItemPriorityR\bpriority\x12\x1f\n" +
	"\vassignee_id\x18\b \x01(\tR\n" +
	"assigneeId\x12\x1f\n" +
	"\vreporter_id\x18\t \x01(\tR\n" +
	"reporterId\x12!\n" +
	"\fstory_points\x18\n" +
	" \x01(\x05R\vstoryPoints\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x123\n" +
	"\bfeatures\x18\r \x01(\v2\x17.google.protobuf.StructR\bfeatures\"V\n" +
	"\x15CreateWorkItemRequest\x12=\n" +
	"\twork_item\x18\x01 \x01(\v2 .chura.workitem.v1.WorkItemInputR\bworkItem\"f\n" +
	"\x15UpdateWorkItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\twork_item\x18\x02 \x01(\v2 .chura.workitem.v1.WorkItemInputR\bworkItem\"\xb1\x03\n" +
	"\rWorkItemInput\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1f.chura.workitem.v1.WorkItemTypeR\x04type\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.chura.workitem.v1.WorkItemStatusR\x06status\x12?\n" +
	"\bpriority\x18\x06 \x01(\x0e2#.chura.workitem.v1.WorkItemPriorityR\bpriority\x12\x1f\n" +
	"\vassignee_id\x18\a \x01(\tR\n" +
	"assigneeId\x12\x1f\n" +
	"\vreporter_id\x18\b \x01(\tR\n" +
	"reporterId\x12!\n" +
	"\fstory_points\x18\t \x01(\x05R\vstoryPoints\x123\n" +
	"\bfeatures\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bfeatures\"$\n" +
	"\x12GetWorkItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x14ListWorkItemsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"S\n" +
	"\x15ListWorkItemsResponse\x12:\n" +
	"\n" +
	"work_items\x18\x01 \x03(\v2\x1b.chura.workitem.v1.WorkItemR\tworkItems\"'\n" +
	"\x15DeleteWorkItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*Q\n" +
	"\fWorkItemType\x12\x1e\n" +
	"\x1aWORK_ITEM_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04TASK\x10\x01\x12\x0e\n" +
	"\n" +
	"USER_STORY\x10\x02\x12\a\n" +
	"\x03BUG\x10\x03*q\n" +
	"\x0eWorkItemStatus\x12 \n" +
	"\x1cWORK_ITEM_STATUS_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05TO_DO\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x03\x12\b\n" +
	"\x04DONE\x10\x04\x12\v\n" +
	"\aBLOCKED\x10\x05*c\n" +
	"\x10WorkItemPriority\x12\"\n" +
	"\x1eWORK_ITEM_PRIORITY_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x042\xd3\x03\n" +
	"\x0fWorkItemService\x12\\\n" +
	"\x0fCreateWorkItems\x12(.chura.workitem.v1.CreateWorkItemRequest\x1a\x1b.chura.workitem.v1.WorkItem(\x010\x01\x12Q\n" +
	"\vGetWorkItem\x12%.chura.workitem.v1.GetWorkItemRequest\x1a\x1b.chura.workitem.v1.WorkItem\x12b\n" +
	"\rListWorkItems\x12'.chura.workitem.v1.ListWorkItemsRequest\x1a(.chura.workitem.v1.ListWorkItemsResponse\x12W\n" +
	"\x0eUpdateWorkItem\x12(.chura.workitem.v1.UpdateWorkItemRequest\x1a\x1b.chura.workitem.v1.WorkItem\x12R\n" +
	"\x0eDeleteWorkItem\x12(.chura.workitem.v1.DeleteWorkItemRequest\x1a\x16.google.protobuf.EmptyBPZNgithub.com/RookieJoel/Chura/backend/internal/adapter/grpc/pb/workitem;workitemb\x06proto3"

var (
	file_internal_adapter_grpc_proto_workitem_proto_rawDescOnce sync.Once
	file_internal_adapter_grpc_proto_workitem_proto_rawDescData []byte
)

func file_internal_adapter_grpc_proto_workitem_proto_rawDescGZIP() []byte {
	file_internal_adapter_grpc_proto_workitem_proto_rawDescOnce.Do(func() {
		file_internal_adapter_grpc_proto_workitem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapter_grpc_proto_workitem_proto_rawDesc), len(file_internal_adapter_grpc_proto_workitem_proto_rawDesc)))
	})
	return file_internal_adapter_grpc_proto_workitem_proto_rawDescData
}

var file_internal_adapter_grpc_proto_workitem_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_adapter_grpc_proto_workitem_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_adapter_grpc_proto_workitem_proto_goTypes = []any{
	(WorkItemType)(0),             // 0: chura.workitem.v1.WorkItemType
	(WorkItemStatus)(0),           // 1: chura.workitem.v1.WorkItemStatus
	(WorkItemPriority)(0),         // 2: chura.workitem.v1.WorkItemPriority
	(*WorkItem)(nil),              // 3: chura.workitem.v1.WorkItem
	(*CreateWorkItemRequest)(nil), // 4: chura.workitem.v1.CreateWorkItemRequest
	(*UpdateWorkItemRequest)(nil), // 5: chura.workitem.v1.UpdateWorkItemRequest
	(*WorkItemInput)(nil),         // 6: chura.workitem.v1.WorkItemInput
	(*GetWorkItemRequest)(nil),    // 7: chura.workitem.v1.GetWorkItemRequest
	(*ListWorkItemsRequest)(nil),  // 8: chura.workitem.v1.ListWorkItemsRequest
	(*ListWorkItemsResponse)(nil), // 9: chura.workitem.v1.ListWorkItemsResponse
	(*DeleteWorkItemRequest)(nil), // 10: chura.workitem.v1.DeleteWorkItemRequest
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 12: google.protobuf.Struct
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_internal_adapter_grpc_proto_workitem_proto_depIdxs = []int32{
	0,  // 0: chura.workitem.v1.WorkItem.type:type_name -> chura.workitem.v1.WorkItemType
	1,  // 1: chura.workitem.v1.WorkItem.status:type_name -> chura.workitem.v1.WorkItemStatus
	2,  // 2: chura.workitem.v1.WorkItem.priority:type_name -> chura.workitem.v1.WorkItemPriority
	11, // 3: chura.workitem.v1.WorkItem.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: chura.workitem.v1.WorkItem.updated_at:type_name -> google.protobuf.Timestamp
	12, // 5: chura.workitem.v1.WorkItem.features:type_name -> google.protobuf.Struct
	6,  // 6: chura.workitem.v1.CreateWorkItemRequest.work_item:type_name -> chura.workitem.v1.WorkItemInput
	6,  // 7: chura.workitem.v1.UpdateWorkItemRequest.work_item:type_name -> chura.workitem.v1.WorkItemInput
	0,  // 8: chura.workitem.v1.WorkItemInput.type:type_name -> chura.workitem.v1.WorkItemType
	1,  // 9: chura.workitem.v1.WorkItemInput.status:type_name -> chura.workitem.v1.WorkItemStatus
	2,  // 10: chura.workitem.v1.WorkItemInput.priority:type_name -> chura.workitem.v1.WorkItemPriority
	12, // 11: chura.workitem.v1.WorkItemInput.features:type_name -> google.protobuf.Struct
	3,  // 12: chura.workitem.v1.ListWorkItemsResponse.work_items:type_name -> chura.workitem.v1.WorkItem
	4,  // 13: chura.workitem.v1.WorkItemService.CreateWorkItems:input_type -> chura.workitem.v1.CreateWorkItemRequest
	7,  // 14: chura.workitem.v1.WorkItemService.GetWorkItem:input_type -> chura.workitem.v1.GetWorkItemRequest
	8,  // 15: chura.workitem.v1.WorkItemService.ListWorkItems:input_type -> chura.workitem.v1.ListWorkItemsRequest
	5,  // 16: chura.workitem.v1.WorkItemService.UpdateWorkItem:input_type -> chura.workitem.v1.UpdateWorkItemRequest
	10, // 17: chura.workitem.v1.WorkItemService.DeleteWorkItem:input_type -> chura.workitem.v1.DeleteWorkItemRequest
	3,  // 18: chura.workitem.v1.WorkItemService.CreateWorkItems:output_type -> chura.workitem.v1.WorkItem
	3,  // 19: chura.workitem.v1.WorkItemService.GetWorkItem:output_type -> chura.workitem.v1.WorkItem
	9,  // 20: chura.workitem.v1.WorkItemService.ListWorkItems:output_type -> chura.workitem.v1.ListWorkItemsResponse
	3,  // 21: chura.workitem.v1.WorkItemService.UpdateWorkItem:output_type -> chura.workitem.v1.WorkItem
	13, // 22: chura.workitem.v1.WorkItemService.DeleteWorkItem:output_type -> google.protobuf.Empty
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_adapter_grpc_proto_workitem_proto_init() }
func file_internal_adapter_grpc_proto_workitem_proto_init() {
	if File_internal_adapter_grpc_proto_workitem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapter_grpc_proto_workitem_proto_rawDesc), len(file_internal_adapter_grpc_proto_workitem_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapter_grpc_proto_workitem_proto_goTypes,
		DependencyIndexes: file_internal_adapter_grpc_proto_workitem_proto_depIdxs,
		EnumInfos:         file_internal_adapter_grpc_proto_workitem_proto_enumTypes,
		MessageInfos:      file_internal_adapter_grpc_proto_workitem_proto_msgTypes,
	}.Build()
	File_internal_adapter_grpc_proto_workitem_proto = out.File
	file_internal_adapter_grpc_proto_workitem_proto_goTypes = nil
	file_internal_adapter_grpc_proto_workitem_proto_depIdxs = nil
}
