import type {
  Member,
  Sprint,
  WorkItem,
  WorkItemComment,
} from "@/types/work-item";

/**
 * Fixtures backing the `src/api` layer until the real Work Item API lands.
 * Shapes mirror what that API is expected to return so swapping the fetch
 * implementation later shouldn't require touching any page or component.
 */

export const members: Member[] = [
  { id: "amorn", name: "Amorn Phanturat", initials: "AP", color: "#F79009" },
  { id: "suttanop", name: "Suttanop Chanah", initials: "SC", color: "#2E90FA" },
  { id: "jirapat", name: "Jirapat Dangkowkiew", initials: "JD", color: "#12B76A" },
  { id: "akarawat", name: "Akarawat Pongchaikaikiti", initials: "AK", color: "#9E5CF7" },
  { id: "akkharachai", name: "Akkharachai Yongsuwankul", initials: "AY", color: "#0BA5A4" },
];

export const sprints: Sprint[] = [
  {
    id: "sprint-4",
    name: "Sprint 4",
    startDate: "2026-09-15",
    endDate: "2026-09-29",
    status: "active",
  },
];

export const activeSprintId = "sprint-4";

export const workItems: WorkItem[] = [
  {
    id: "CHURA-101",
    type: "story",
    title: "As a team member, I want to create a Work Item so I can plan the Backlog",
    status: "review",
    blocked: false,
    priority: "high",
    storyPoints: 5,
    epic: "Backlog",
    assigneeId: "jirapat",
    reporterId: "jirapat",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-10",
    updatedAt: "2026-09-19",
  },
  {
    id: "CHURA-102",
    type: "task",
    title: "Add Work Item type selector (Story / Task / Bug)",
    status: "in_progress",
    blocked: false,
    priority: "medium",
    storyPoints: 3,
    epic: "Backlog",
    assigneeId: "amorn",
    reporterId: "jirapat",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-10",
    updatedAt: "2026-09-18",
  },
  {
    id: "CHURA-103",
    type: "story",
    title: "As a team member, I want to add Acceptance Criteria to a User Story",
    status: "done",
    blocked: false,
    priority: "high",
    storyPoints: 8,
    epic: "Backlog",
    assigneeId: "suttanop",
    reporterId: "jirapat",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-08",
    updatedAt: "2026-09-16",
  },
  {
    id: "CHURA-104",
    type: "bug",
    title: "Story Point field accepts negative values",
    status: "done",
    blocked: false,
    priority: "highest",
    storyPoints: 2,
    epic: "Backlog",
    assigneeId: "akarawat",
    reporterId: "suttanop",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-11",
    updatedAt: "2026-09-15",
  },
  {
    id: "CHURA-105",
    type: "task",
    title: "Drag-and-drop reordering in Backlog",
    status: "in_progress",
    blocked: false,
    priority: "medium",
    storyPoints: 5,
    epic: "Backlog",
    assigneeId: "akkharachai",
    reporterId: "jirapat",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-12",
    updatedAt: "2026-09-19",
  },
  {
    id: "CHURA-106",
    type: "story",
    title: "As a team member, I want to move Work Items between Sprint Board columns",
    status: "review",
    blocked: false,
    priority: "high",
    storyPoints: 5,
    epic: "Sprint Board",
    assigneeId: "jirapat",
    reporterId: "jirapat",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-09",
    updatedAt: "2026-09-20",
  },
  {
    id: "CHURA-107",
    type: "task",
    title: "Kanban status transitions (To Do → In Progress → Review → Done)",
    status: "in_progress",
    blocked: false,
    priority: "medium",
    storyPoints: 3,
    epic: "Sprint Board",
    assigneeId: "amorn",
    reporterId: "jirapat",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-09",
    updatedAt: "2026-09-18",
  },
  {
    id: "CHURA-108",
    type: "bug",
    title: "Card story points not summing correctly per column",
    status: "done",
    blocked: false,
    priority: "high",
    storyPoints: 2,
    epic: "Sprint Board",
    assigneeId: "suttanop",
    reporterId: "amorn",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-13",
    updatedAt: "2026-09-17",
  },
  {
    id: "CHURA-109",
    type: "story",
    title: "As a team member, I want to mark a Work Item as Blocked with a reason",
    description:
      "Team members need a way to flag a Work Item as unable to progress. When a ticket is marked Blocked, the system should require a short reason so the rest of the team can see why work has stalled during Sprint execution.",
    status: "todo",
    blocked: false,
    priority: "medium",
    storyPoints: 3,
    epic: "Sprint Board",
    assigneeId: "akarawat",
    reporterId: "jirapat",
    sprintId: activeSprintId,
    labels: ["workflow", "backlog"],
    acceptanceCriteria: [
      { text: 'Team member can select "Blocked" from the status control', done: true },
      { text: "A reason is required when marking a Work Item as Blocked", done: true },
      { text: "Blocked reason is visible on the Board card", done: false },
      { text: "Blocked status change is recorded in the Work Item history", done: false },
    ],
    createdAt: "2026-09-16",
    updatedAt: "2026-09-20",
  },
  {
    id: "CHURA-110",
    type: "task",
    title: "Add Blocked reason modal",
    status: "todo",
    blocked: false,
    priority: "low",
    storyPoints: 2,
    epic: "Sprint Board",
    assigneeId: "akkharachai",
    reporterId: "akarawat",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-16",
    updatedAt: "2026-09-16",
  },
  {
    id: "CHURA-111",
    type: "story",
    title: "As an auditor, I want to view project health so I can assess team progress",
    status: "todo",
    blocked: false,
    priority: "high",
    storyPoints: 8,
    epic: "Reporting",
    reporterId: "jirapat",
    sprintId: null,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-14",
    updatedAt: "2026-09-14",
  },
  {
    id: "CHURA-112",
    type: "task",
    title: "Build Sprint Burndown chart",
    status: "in_progress",
    blocked: false,
    priority: "medium",
    storyPoints: 5,
    epic: "Reporting",
    assigneeId: "amorn",
    reporterId: "jirapat",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-11",
    updatedAt: "2026-09-19",
  },
  {
    id: "CHURA-113",
    type: "bug",
    title: "Burndown shows incorrect remaining points after Sprint edit",
    status: "in_progress",
    blocked: true,
    blockedReason: "Waiting on CHURA-112 to land so the fix can be verified against real burndown data.",
    priority: "highest",
    storyPoints: 3,
    epic: "Reporting",
    assigneeId: "suttanop",
    reporterId: "amorn",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-17",
    updatedAt: "2026-09-20",
  },
  {
    id: "CHURA-114",
    type: "story",
    title: "As a team member, I want Story Point estimation guidance",
    status: "todo",
    blocked: false,
    priority: "medium",
    storyPoints: 5,
    epic: "Backlog",
    assigneeId: "akarawat",
    reporterId: "jirapat",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-15",
    updatedAt: "2026-09-15",
  },
  {
    id: "CHURA-115",
    type: "task",
    title: "Implement Sprint Review Summary export",
    status: "review",
    blocked: false,
    priority: "low",
    storyPoints: 3,
    epic: "Reporting",
    assigneeId: "akkharachai",
    reporterId: "jirapat",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-12",
    updatedAt: "2026-09-18",
  },
  {
    id: "CHURA-116",
    type: "task",
    title: "Add Work Item filter by assignee on Board",
    status: "todo",
    blocked: false,
    priority: "low",
    storyPoints: 2,
    epic: "Sprint Board",
    assigneeId: "jirapat",
    reporterId: "amorn",
    sprintId: activeSprintId,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-16",
    updatedAt: "2026-09-16",
  },
  {
    id: "CHURA-117",
    type: "story",
    title: "As a team member, I want to filter the Backlog by Epic",
    status: "todo",
    blocked: false,
    priority: "low",
    storyPoints: 3,
    epic: "Backlog",
    reporterId: "jirapat",
    sprintId: null,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-18",
    updatedAt: "2026-09-18",
  },
  {
    id: "CHURA-118",
    type: "task",
    title: "Add empty state illustration for empty Backlog",
    status: "todo",
    blocked: false,
    priority: "low",
    storyPoints: 2,
    epic: "Backlog",
    reporterId: "amorn",
    sprintId: null,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-18",
    updatedAt: "2026-09-18",
  },
  {
    id: "CHURA-119",
    type: "bug",
    title: "Long Work Item titles overflow the card on mobile",
    status: "todo",
    blocked: false,
    priority: "medium",
    storyPoints: 2,
    epic: "Sprint Board",
    reporterId: "suttanop",
    sprintId: null,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-19",
    updatedAt: "2026-09-19",
  },
  {
    id: "CHURA-120",
    type: "story",
    title: "As an auditor, I want to leave comments on a Work Item",
    status: "todo",
    blocked: false,
    priority: "medium",
    storyPoints: 5,
    epic: "Reporting",
    reporterId: "jirapat",
    sprintId: null,
    labels: [],
    acceptanceCriteria: [],
    createdAt: "2026-09-20",
    updatedAt: "2026-09-20",
  },
];

export const comments: WorkItemComment[] = [
  {
    id: "c1",
    workItemId: "CHURA-109",
    authorId: "jirapat",
    body: "Should the reason be a free-text field, or a short list of common blockers (waiting on review, dependency, environment)?",
    createdAt: "2026-09-19T10:42:00Z",
  },
  {
    id: "c2",
    workItemId: "CHURA-109",
    authorId: "akarawat",
    body: "Let's start with free text — we can add presets later if patterns show up in Sprint reviews.",
    createdAt: "2026-09-20T09:15:00Z",
  },
];
